version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    links:
      - database
    environment:
      RAILS_ENV: development
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: 1783
      DB_HOST: database
      
  database:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 1783
        MYSQL_DATABASE: app
        MYSQL_USER: user
        MYSQL_PASSWORD: 1783
    ports:
        - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      
volumes:
  gem_cache:
  db_data:
  node_modules: 